In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.preprocessing import StandardScaler
import statsmodels.formula.api as smf
import statsmodels.api as sm
import sys
from sqlalchemy import create_engine, text

sys.path.append("..")
from nhanes_analysis import load_analysis_data, run_correlation, run_scatter, run_linear_regression, run_logistic_regression
sys.path.append("..")
from diagnosis_config import DISEASE_CONFIGS

# -------------------------------
# CONFIG
# -------------------------------

DB_URI = 'postgresql://postgres:rsc@localhost:5432/NHANES_20172020'
engine = create_engine(DB_URI)

In [2]:
%load_ext sql

In [3]:
%sql postgresql://postgres:rsc@localhost:5432/NHANES_20172020

Connecting to 'postgresql://postgres:***@localhost:5432/NHANES_20172020'

In [4]:
%%sql

DELETE FROM biomarker_registry
WHERE biomarker_name LIKE '%comment_code%';

Running query in 'postgresql://postgres:***@localhost:5432/NHANES_20172020'

++
||
++
++

In [5]:
%%sql 

SELECT biomarker_name, unit, source_table
FROM biomarker_registry
WHERE biomarker_name LIKE '%albumin%'
   OR biomarker_name LIKE '%creatinine%'
   OR biomarker_name LIKE '%iodine%'
ORDER BY biomarker_name;

Running query in 'postgresql://postgres:***@localhost:5432/NHANES_20172020'

6 rows affected.

+-------------------------------+-------+------------------+
|         biomarker_name        |  unit |   source_table   |
+-------------------------------+-------+------------------+
|    albumin_creatinine_ratio   |  mg/g | raw_urine_albcr  |
|   albumin_refrigerated_serum  |  g/dL |  raw_blood_cmp   |
|         albumin_urine         | ug/mL | raw_urine_albcr  |
| creatinine_refrigerated_serum | mg/dL |  raw_blood_cmp   |
|        creatinine_urine       | mg/dL | raw_urine_albcr  |
|          iodine_urine         |  ug/L | raw_urine_iodine |
+-------------------------------+-------+------------------+

In [6]:
load_analysis_data(["albumin_urine", "creatinine_urine", "iodine_urine"], 'obesity', engine)

After age filter (>= 18): 8,731 participants
After dropping missing values: 2,898 (5,833 dropped)

,participant_id,bmi,age,sex,race_ethnicity,albumin_urine,creatinine_urine,iodine_urine,obese
0,109266.0,37.8,29.0,2.0,6.0,5.5,36.0,50.6,1
3,109273.0,21.9,36.0,1.0,3.0,4.9,121.0,71.3,0
4,109274.0,30.2,68.0,1.0,7.0,12.8,120.0,265.3,1
15,109290.0,28.1,68.0,2.0,4.0,22.4,272.0,122.4,0
18,109295.0,24.9,54.0,2.0,1.0,13.0,50.0,198.0,0
...,...,...,...,...,...,...,...,...,...
12493,124798.0,26.0,55.0,1.0,2.0,7.2,164.0,63.5,0
12494,124799.0,23.9,80.0,2.0,3.0,307.5,96.0,119.4,0
12500,124809.0,27.1,23.0,2.0,1.0,12.3,224.0,106.4,0
12503,124812.0,28.7,62.0,2.0,2.0,19.5,69.0,116.8,0
12510,124821.0,25.5,63.0,1.0,4.0,6.1,191.0,221.5,0

In [7]:
biomarkers = ["albumin_urine", "creatinine_urine", "iodine_urine"]

corr_results = run_correlation(
    biomarkers=biomarkers,
    disease="obesity",
    engine=engine,
    method="spearman"
)

After age filter (>= 18): 8,731 participants
After dropping missing values: 2,898 (5,833 dropped)

Spearman Correlation — Obesity
       biomarker outcome  correlation  p_value    n  log_transform   method  significant
   albumin_urine     bmi       0.1520 0.000000 2846          False spearman         True
creatinine_urine     bmi       0.1497 0.000000 2846          False spearman         True
    iodine_urine     bmi       0.0899 0.000002 2846          False spearman         True

In [8]:
corr_pearson = run_correlation(
    biomarkers=["albumin_urine", "creatinine_urine", "iodine_urine"],
    disease="obesity",
    engine=engine,
    method="pearson",
    log_transform=False
)

After age filter (>= 18): 8,731 participants
After dropping missing values: 2,898 (5,833 dropped)

Pearson Correlation — Obesity
       biomarker outcome  correlation  p_value    n  log_transform  method  significant
creatinine_urine     bmi       0.1446 0.000000 2846          False pearson         True
   albumin_urine     bmi       0.0319 0.088688 2846          False pearson        False
    iodine_urine     bmi       0.0026 0.890474 2846          False pearson        False

In [9]:
corr_log_pearson = run_correlation(
    biomarkers=["albumin_urine", "creatinine_urine", "iodine_urine"],
    disease="obesity",
    engine=engine,
    method="pearson",
    log_transform=True
)

After age filter (>= 18): 8,731 participants
After dropping missing values: 2,898 (5,833 dropped)

Pearson Correlation — Obesity
       biomarker outcome  correlation  p_value    n  log_transform  method  significant
creatinine_urine     bmi       0.1632 0.000000 2846           True pearson         True
   albumin_urine     bmi       0.1516 0.000000 2846           True pearson         True
    iodine_urine     bmi       0.0846 0.000006 2846           True pearson         True

In [10]:
%%sql

SELECT biomarker_name, unit, source_table
FROM biomarker_registry
WHERE biomarker_name LIKE '%glucose%'
   OR biomarker_name LIKE '%insulin%'
   OR biomarker_name LIKE '%glyco%'
   OR biomarker_name LIKE '%hba1c%'
   OR biomarker_name LIKE '%hemoglobin%'
ORDER BY biomarker_name;

Running query in 'postgresql://postgres:***@localhost:5432/NHANES_20172020'

6 rows affected.

+----------------------------+--------+---------------------------+
|       biomarker_name       |  unit  |        source_table       |
+----------------------------+--------+---------------------------+
|  alpha1acid_glycoprotein   |  g/L   |       raw_blood_agp       |
|      fasting_glucose       | mg/dL  | raw_blood_fasting_glucose |
| glucose_refrigerated_serum | mg/dL  |       raw_blood_cmp       |
|      glycohemoglobin       |   %    | raw_blood_glycohemoglobin |
|         hemoglobin         |  g/dL  |       raw_blood_cbc       |
|          insulin           | Î¼U/mL |     raw_blood_insulin     |
+----------------------------+--------+---------------------------+

In [12]:
run_correlation(
    biomarkers=["fasting_glucose", "glycohemoglobin", "insulin"],
    disease="obesity",
    engine=engine,
    method="pearson",
    log_transform=False,
    filters={
        "min_age": 18,
        "exclude_diabetes": True
    }
)

After age filter (>= 18): 8,475 participants
After dropping missing values: 4,057 (4,418 dropped)

Pearson Correlation — Obesity
      biomarker outcome  correlation  p_value    n  log_transform  method  significant
        insulin     bmi       0.2974      0.0 3986          False pearson         True
glycohemoglobin     bmi       0.2039      0.0 3986          False pearson         True
fasting_glucose     bmi       0.1856      0.0 3986          False pearson         True

,biomarker,outcome,correlation,p_value,n,log_transform,method,significant
2,insulin,bmi,0.2974,0.0,3986,False,pearson,True
1,glycohemoglobin,bmi,0.2039,0.0,3986,False,pearson,True
0,fasting_glucose,bmi,0.1856,0.0,3986,False,pearson,True

In [13]:
%%sql

SELECT biomarker_name, raw_col, unit, source_table
FROM biomarker_registry
WHERE biomarker_name LIKE '%insulin%';

Running query in 'postgresql://postgres:***@localhost:5432/NHANES_20172020'

1 rows affected.

+----------------+---------+--------+-------------------+
| biomarker_name | raw_col |  unit  |    source_table   |
+----------------+---------+--------+-------------------+
|    insulin     |  LBXIN  | Î¼U/mL | raw_blood_insulin |
+----------------+---------+--------+-------------------+